import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";

import { Roboto } from "next/font/google"

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],

  variable: "--font-roboto",
});

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} bg-background antialiased overflow-x-hidden `}
      >
        {children}
      </body>
    </html>
  );
}
